// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBjOPJNYcS8C4TZ2ydvv7gjfvRcGWUMuU',
    appId: '1:342148343099:web:9742e25079fdbbdf66831e',
    messagingSenderId: '342148343099',
    projectId: 'shift-kobo-online',
    authDomain: 'shift-kobo-online.firebaseapp.com',
    storageBucket: 'shift-kobo-online.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPvJTBOuhhlM50qmji_ZFgDe2k0bhK2yE',
    appId: '1:342148343099:android:6a56d7a980a4807966831e',
    messagingSenderId: '342148343099',
    projectId: 'shift-kobo-online',
    storageBucket: 'shift-kobo-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4qN0RNC6TVc8lhmtKwXA5QisjWRNFVEA',
    appId: '1:342148343099:ios:c57d21ecbfc413b966831e',
    messagingSenderId: '342148343099',
    projectId: 'shift-kobo-online',
    storageBucket: 'shift-kobo-online.firebasestorage.app',
    iosBundleId: 'io.github.shitakahashi.shiftkobo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4qN0RNC6TVc8lhmtKwXA5QisjWRNFVEA',
    appId: '1:342148343099:ios:ad9243e72ac9164966831e',
    messagingSenderId: '342148343099',
    projectId: 'shift-kobo-online',
    storageBucket: 'shift-kobo-online.firebasestorage.app',
    iosBundleId: 'com.example.shiftKobo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBjOPJNYcS8C4TZ2ydvv7gjfvRcGWUMuU',
    appId: '1:342148343099:web:bcc1be119b00bd4b66831e',
    messagingSenderId: '342148343099',
    projectId: 'shift-kobo-online',
    authDomain: 'shift-kobo-online.firebaseapp.com',
    storageBucket: 'shift-kobo-online.firebasestorage.app',
  );
}
