import 'package:flutter/material.dart';
// import 'package:google_mobile_ads/google_mobile_ads.dart'; // 一時的にコメントアウト
import 'calendar_screen.dart';
import 'staff_list_screen.dart';
import 'settings_screen.dart';
import '../widgets/auto_assignment_dialog.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _selectedIndex = 0;
  
  // 一時的にコメントアウト
  // late BannerAd _bannerAd;
  // bool _isBannerAdReady = false;

  final List<Widget> _screens = [
    const CalendarScreen(),
    const StaffListScreen(),
    const SettingsScreen(),
  ];

  final List<String> _titles = [
    'シフト表',
    'スタッフ管理',
    '設定',
  ];

  @override
  void initState() {
    super.initState();
    // _loadBannerAd(); // 一時的にコメントアウト
  }

  // void _loadBannerAd() {
  //   _bannerAd = BannerAd(
  //     adUnitId: 'ca-app-pub-3940256099942544/6300978111',
  //     request: const AdRequest(),
  //     size: AdSize.banner,
  //     listener: BannerAdListener(
  //       onAdLoaded: (_) {
  //         setState(() {
  //           _isBannerAdReady = true;
  //         });
  //       },
  //       onAdFailedToLoad: (ad, err) {
  //         _isBannerAdReady = false;
  //         ad.dispose();
  //       },
  //     ),
  //   );
  //   _bannerAd.load();
  // }

  @override
  void dispose() {
    // _bannerAd.dispose(); // 一時的にコメントアウト
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(_titles[_selectedIndex], style: const TextStyle(fontSize: 18)),
        toolbarHeight: 48, // デフォルト56 → 48に縮小
        actions: [
          IconButton(
            icon: const Icon(Icons.help_outline, size: 22),
            onPressed: () {
              _showHelpDialog();
            },
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: _screens[_selectedIndex],
          ),
          // バナー広告領域を確保（現在は薄いグレーで表示）
          Container(
            width: double.infinity,
            height: 50, // 標準的なバナー広告の高さ
            color: Colors.grey.shade100,
            child: const Center(
              child: Text(
                'バナー広告領域',
                style: TextStyle(
                  color: Colors.grey,
                  fontSize: 12,
                ),
              ),
            ),
          ),
        ],
      ),
      bottomNavigationBar: NavigationBar(
        height: 65, // デフォルト80 → 65に縮小
        onDestinationSelected: (int index) {
          setState(() {
            _selectedIndex = index;
          });
        },
        selectedIndex: _selectedIndex,
        destinations: const <Widget>[
          NavigationDestination(
            icon: Icon(Icons.calendar_month, size: 22),
            label: 'シフト',
          ),
          NavigationDestination(
            icon: Icon(Icons.people, size: 22),
            label: 'スタッフ',
          ),
          NavigationDestination(
            icon: Icon(Icons.settings, size: 22),
            label: '設定',
          ),
        ],
      ),
      floatingActionButton: _buildFloatingActionButton(),
    );
  }

  Widget? _buildFloatingActionButton() {
    if (_selectedIndex == 1) {
      return FloatingActionButton(
        onPressed: () {
          Navigator.pushNamed(context, '/add_staff');
        },
        child: const Icon(Icons.person_add),
      );
    }
    return null;
  }

  void _showAutoGenerateDialog() {
    showDialog<bool>(
      context: context,
      builder: (context) => AutoAssignmentDialog(
        selectedMonth: DateTime.now(),
      ),
    ).then((result) {
      if (result == true) {
        setState(() {});
      }
    });
  }

  void _showHelpDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('使い方'),
        content: const SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('1. スタッフ管理でスタッフを登録'),
              SizedBox(height: 8),
              Text('2. カレンダーでシフトを自動作成'),
              SizedBox(height: 8),
              Text('3. 必要に応じて手動で調整'),
              SizedBox(height: 8),
              Text('4. 完成したシフト表を共有'),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('閉じる'),
          ),
        ],
      ),
    );
  }
}